import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/pages/layout/Header";
import { ReactQuery } from "@/context/ReackQuery";
import Recoil from "@/context/Recoil";
import { Footer } from "@/components/common/icon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQuery>
          <Recoil>
            <Header />
            {children}
          </Recoil>
        </ReactQuery>
        <Footer />
      </body>
    </html>
  );
}
