import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/pages/layout/Header";
import { ReactQuery } from "@/context/ReackQuery";
import Recoil from "@/context/Recoil";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQuery>
          <Recoil>
            <Header />
            {children}
          </Recoil>
        </ReactQuery>
      </body>
    </html>
  );
}
