INSERT INTO university_tb (id, name, region) VALUES (1, '삼육보건대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (2, '서울여자간호대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (3, '동주대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (4, '기독간호대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (5, '조선간호대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (6, '세경대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (7, '강동대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (8, '백석문화대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (9, '군산간호대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (10, '동아보건대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (11, '순천제일대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (12, '동양미래대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (13, '명전문대학', '서울');
INSERT INTO university_tb (id, name, region) VALUES (14, '배화여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (15, '경남정보대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (16, '대구보건대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (17, '수성대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (18, '경인여자대학교', '인천');
INSERT INTO university_tb (id, name, region) VALUES (20, '광주보건대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (21, '동강대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (19, '인하공업전문대', '인천');
INSERT INTO university_tb (id, name, region) VALUES (22, '서영대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (23, '대전과학기술대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (24, '우송정보대학', '대전');
INSERT INTO university_tb (id, name, region) VALUES (25, '울산과학대학교', '울산');
INSERT INTO university_tb (id, name, region) VALUES (26, '춘해보건대학교', '울산');
INSERT INTO university_tb (id, name, region) VALUES (27, '한국영상대학교', '세종');
INSERT INTO university_tb (id, name, region) VALUES (28, '경민대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (29, '경복대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (30, '김포대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (31, '농협대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (32, '대림대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (33, '동남보건대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (34, '동아송예술대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (35, '동원대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (36, '서울예술대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (37, '서정대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (38, '수원과학대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (39, '신구대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (40, '안산대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (41, '연성대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (42, '오산대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (43, '용인송담대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (44, '웅지세무대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (45, '청강문화산업대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (46, '한국복지대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (47, '강릉영동대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (48, '강원도립대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (49, '한국골프대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (50, '한림성심대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (51, '충북보건과학대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (52, '신성대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (53, '충남도립대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (54, '혜전대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (55, '군장대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (56, '서해대학', '전북');
INSERT INTO university_tb (id, name, region) VALUES (57, '원광보건대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (58, '전주기전대학', '전북');
INSERT INTO university_tb (id, name, region) VALUES (59, '한국농수산대학', '전북');
INSERT INTO university_tb (id, name, region) VALUES (60, '고구려대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (61, '광양보건대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (62, '목포과학대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (63, '청암대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (64, '가톨릭상지대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (65, '경북전문대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (66, '선린대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (67, '성운대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (68, '안동과학대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (69, '포항대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (70, '거제대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (71, '김해대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (72, '마산대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (73, '연암공과대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (74, '진주보건대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (75, '창원문성대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (76, '제주한라대학교', '제주');
INSERT INTO university_tb (id, name, region) VALUES (77, '서일대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (78, '숭의여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (79, '인덕대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (80, '한양여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (81, '대동대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (82, '동의과학대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (83, '부산경상대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (84, '부산과학기술대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (85, '부산여자대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (86, '부산예술대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (87, '성심외국어대학', '부산');
INSERT INTO university_tb (id, name, region) VALUES (88, '계명문화대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (89, '대구공업대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (90, '대구과학대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (91, '영남이공대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (92, '영진전문대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (93, '인천재능대학교', '인천');
INSERT INTO university_tb (id, name, region) VALUES (94, '조선이공대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (95, '대덕대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (96, '대전보건대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (97, '경기과학기술대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (98, '계원예술대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (99, '국제대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (100, '동서울대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (101, '두원공과대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (102, '부천대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (103, '수원여자대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (104, '신안산대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (105, '신흥대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (106, '여주대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (107, '유한대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (108, '장안대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (109, '한국관광대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (110, '강원관광대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (111, '상지영서대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (112, '송곡대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (113, '송호대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (114, '대원대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (115, '충북도립대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (116, '충청대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (117, '아주자동차대학', '충남');
INSERT INTO university_tb (id, name, region) VALUES (118, '연암대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (119, '백제예술대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (120, '전북과학대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (121, '전주비전대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (122, '전남과학대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (123, '전남도립대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (124, '한영대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (125, '경북과학대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (126, '경북도립대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (127, '경북보건대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (128, '구미대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (129, '대경대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (130, '문경대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (131, '서라벌대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (132, '영남외국어대학', '경북');
INSERT INTO university_tb (id, name, region) VALUES (133, '호산대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (134, '경남도립거창대학', '경남');
INSERT INTO university_tb (id, name, region) VALUES (135, '경남도립남해대학', '경남');
INSERT INTO university_tb (id, name, region) VALUES (136, '동원과학기술대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (137, '한국승강기대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (138, '제주관광대학교', '제주');
INSERT INTO university_tb (id, name, region) VALUES (139, '서울교육대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (140, '부산교육대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (141, '대구교육대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (142, '세종사이버대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (143, '광주교육대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (144, '경인교육대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (145, '춘천교육대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (146, '청주교육대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (147, '공주교육대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (148, '전주교육대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (149, '진주교육대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (150, '가톨릭대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (151, '숭실사이버대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (152, '감리교신학대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (153, '건국대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (154, '경기대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (155, '경희대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (156, '고려대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (157, '광운대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (158, '국민대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (159, '덕성여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (160, '동국대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (161, '동덕여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (162, '명지대학교 인문캠퍼스', '서울');
INSERT INTO university_tb (id, name, region) VALUES (163, '삼육대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (164, '상명대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (165, '서강대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (166, '서경대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (167, '서울과학기술대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (168, '서울기독대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (169, '서울대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (170, '서울시립대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (171, '서울여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (172, '서울한영대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (173, '성공회대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (174, '성균관대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (175, '성신여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (176, '세종대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (177, '숙명여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (178, '숭실대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (179, '연세대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (180, '이화여자대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (181, '장로회신학대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (182, '중앙대학교 서울캠퍼스', '서울');
INSERT INTO university_tb (id, name, region) VALUES (183, '총신대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (184, '추계예술대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (185, '케이씨대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (186, '한국성서대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (187, '한국외국어대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (188, '한국체육대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (189, '한성대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (190, '한양대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (191, '홍익대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (192, '경성대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (193, '고신대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (194, '동명대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (195, '동서대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (196, '동아대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (197, '동의대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (198, '부경대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (199, '부산가톨릭대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (200, '부산대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (201, '부산외국어대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (202, '신라대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (203, '영산대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (204, '인제대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (205, '한국해양대학교', '부산');
INSERT INTO university_tb (id, name, region) VALUES (206, '경북대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (207, '계명대학교', '대구');
INSERT INTO university_tb (id, name, region) VALUES (208, '대구경북과학기술원', '대구');
INSERT INTO university_tb (id, name, region) VALUES (209, '안양대학교', '인천');
INSERT INTO university_tb (id, name, region) VALUES (210, '인천가톨릭대학교', '인천');
INSERT INTO university_tb (id, name, region) VALUES (211, '인천대학교', '인천');
INSERT INTO university_tb (id, name, region) VALUES (212, '인하대학교', '인천');
INSERT INTO university_tb (id, name, region) VALUES (213, '광신대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (214, '광주과학기술원', '광주');
INSERT INTO university_tb (id, name, region) VALUES (215, '광주대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (216, '광주여자대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (217, '남부대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (218, '송원대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (219, '전남대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (220, '조선대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (221, '호남대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (222, '호남신학대학교', '광주');
INSERT INTO university_tb (id, name, region) VALUES (223, '건양대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (224, '대전대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (225, '대전신학대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (226, '목원대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (227, '배재대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (228, '우송대학교(본교)', '대전');
INSERT INTO university_tb (id, name, region) VALUES (229, '을지대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (230, '충남대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (231, '한국과학기술원', '대전');
INSERT INTO university_tb (id, name, region) VALUES (232, '한국침례신학대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (233, '한남대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (234, '한밭대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (235, '울산과학기술원', '울산');
INSERT INTO university_tb (id, name, region) VALUES (236, '울산대학교', '울산');
INSERT INTO university_tb (id, name, region) VALUES (237, '고려대학교 세종캠퍼스', '세종');
INSERT INTO university_tb (id, name, region) VALUES (238, '대전가톨릭대학교', '세종');
INSERT INTO university_tb (id, name, region) VALUES (239, '홍익대학교 세종캠퍼스', '세종');
INSERT INTO university_tb (id, name, region) VALUES (240, '서울사이버대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (241, '가천대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (242, '서울디지털대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (243, '강남대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (244, '디지털서울문화예술대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (245, '경동대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (246, '단국대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (247, '대진대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (248, '루터대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (249, '명지대학교 자연캠퍼스', '경기');
INSERT INTO university_tb (id, name, region) VALUES (250, '서울신학대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (251, '서울장신대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (252, '성결대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (253, '수원가톨릭대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (254, '수원대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (255, '신경대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (256, '삼성전자공과대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (257, '신한대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (258, '아세아연합신학대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (259, '아주대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (260, 'LH토지주택대학교', '대전');
INSERT INTO university_tb (id, name, region) VALUES (261, '예원예술대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (262, '용인대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (263, 'KDB금융대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (264, '중앙대학교 안성캠퍼스', '경기');
INSERT INTO university_tb (id, name, region) VALUES (265, '중앙승가대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (266, '차의과학대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (267, '칼빈대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (268, '평택대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (269, '한경대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (270, '한국산업기술대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (271, '한국항공대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (272, '한북대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (273, '한세대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (274, '한신대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (275, '삼성중공업공과대학', '경남');
INSERT INTO university_tb (id, name, region) VALUES (276, '협성대학교', '경기');
INSERT INTO university_tb (id, name, region) VALUES (277, '가톨릭관동대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (278, '강릉원주대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (279, '강원대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (280, '포스코기술대학', '전남');
INSERT INTO university_tb (id, name, region) VALUES (281, '상지대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (282, '연세대학교 미래캠퍼스', '강원');
INSERT INTO university_tb (id, name, region) VALUES (283, '한라대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (284, '한림대학교', '강원');
INSERT INTO university_tb (id, name, region) VALUES (285, '현대중공업공과대학', '울산');
INSERT INTO university_tb (id, name, region) VALUES (286, '극동대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (287, '꽃동네대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (288, '서원대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (289, '세명대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (290, '유원대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (291, '중원대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (292, '청주대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (293, '충북대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (294, '한국교원대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (295, '한국교통대학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (296, 'SPC식품과학대학', '서울');
INSERT INTO university_tb (id, name, region) VALUES (297, '공주대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (298, '금강대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (299, '나사렛대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (300, '남서울대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (301, '영남사이버대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (302, '백석대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (303, '순복음총회신학교', '충북');
INSERT INTO university_tb (id, name, region) VALUES (304, '선문대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (305, '순천향대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (306, '중부대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (307, '한국기술교육대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (308, '한국전통문화대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (309, '한서대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (310, '호서대학교', '충남');
INSERT INTO university_tb (id, name, region) VALUES (311, '군산대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (312, '예수대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (313, '한국예술종합학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (314, '우석대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (315, '원광대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (316, '전북대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (317, '전주대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (318, '한일장신대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (319, '광주가톨릭대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (320, '동신대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (321, '목포가톨릭대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (322, '목포대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (323, '목포해양대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (324, '세한대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (325, '순천대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (326, '영산선학대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (327, '한국열린사이버대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (328, '초당대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (329, '한려대학교', '전남');
INSERT INTO university_tb (id, name, region) VALUES (330, '가야대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (331, '경운대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (332, '경일대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (333, '경주대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (334, '금오공과대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (335, '김천대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (336, '대구가톨릭대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (337, '대구대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (338, '대구예술대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (339, '대구한의대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (340, '대신대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (368, '정석대학', '서울');
INSERT INTO university_tb (id, name, region) VALUES (342, '동양대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (343, '안동대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (344, '영남대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (345, '영남신학대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (346, '위덕대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (347, '포항공과대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (348, '한동대학교', '경북');
INSERT INTO university_tb (id, name, region) VALUES (349, '호원대학교', '전북');
INSERT INTO university_tb (id, name, region) VALUES (350, '경남과학기술대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (351, '경남대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (352, '경상대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (353, '부산장신대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (354, '우송대학교(산업대)', '대전');
INSERT INTO university_tb (id, name, region) VALUES (355, '한국방송통신대학교', '서울');
INSERT INTO university_tb (id, name, region) VALUES (356, '창신대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (357, '창원대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (358, '한국국제대학교', '경남');
INSERT INTO university_tb (id, name, region) VALUES (359, '제주국제대학교', '제주');
INSERT INTO university_tb (id, name, region) VALUES (360, '제주대학교', '제주');
INSERT INTO university_tb (id, name, region) VALUES (361, '기린대학교', '광주');
INSERT INTO member_tb(coin, nickname, email, about_me, address, image, password) VALUES (10000,'에코노베이션','asdf@gmail.com','저는 관리자 입니다.', '광주광역시 북구 용봉동','이미지','{bcrypt}$2a$10$TDHSYFfDf8f2YAk.qoxvke94y4KQEITjfq6fvq4AfoYpgw6AQdnCC');
INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (0, 100000, NOW(), '2024-01-26 00:00:00', '2024-01-26 00:00:00', 1, '2024-01-13 00:00:00', 361, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/Image.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/DetailImage.jpg', '일상에서 감정이입하기 좋은 귀여운 디자인으로 구성되어 있습니다. 노트북, 핸드폰, 수첩 등 어디에든 붙일 수 있는 다양한 크기의 스티커가 포함되어 있어 일상에 즐거움을 더해줄 거에요!', '다이어리에 붙일 수 있는 귀여운 스티커', 'GIFT');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (1, '킹받는 오리의 일상', 10000, -1, true);
INSERT INTO item_tb(option_id, item_name) VALUES (1, '[현장수령형] 1월 25일 스토리움 *23#부스');
INSERT INTO item_tb(option_id, item_name) VALUES (1, '스티커 1pc');
INSERT INTO item_tb(option_id, item_name) VALUES (1, '포장지');
INSERT INTO item_tb(option_id, item_name) VALUES (1, '포인트 카드 1pc');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (1, '비오는 날 쌍둥이', 10000, -1, true);
INSERT INTO item_tb(option_id, item_name) VALUES (2, '[현장수령형] 1월 25일 스토리움 *23#부스');
INSERT INTO item_tb(option_id, item_name) VALUES (2, '스티커 1pc');
INSERT INTO item_tb(option_id, item_name) VALUES (2, '포장지');
INSERT INTO item_tb(option_id, item_name) VALUES (2, '포인트 카드 1pc');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (1, '뒝구르르 냥냥이', 10000, -1, true);
INSERT INTO item_tb(option_id, item_name) VALUES (3, '스티커 1pc');
INSERT INTO item_tb(option_id, item_name) VALUES (3, '포장지');
INSERT INTO item_tb(option_id, item_name) VALUES (3, '포인트 카드 1pc');

INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (0, 9999999, NOW(), '2024-01-26 00:00:00', '2024-01-27 00:00:00', 1, '2024-01-13 00:00:00', 361, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/공기.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/공기상세설명_page-0001.jpg', '작년의 공기, 과거의 추억이 녹아있는 맛. 작년 공기를 마시며 과거를 회상하고, 지금의 자신을 발견해 미래를 계획해보세요!','과거의 물결은 바로 지금의 해변을 만든다.', 'GIFT');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (2, '2023공기 1개', 9999999, 1, true);
INSERT INTO item_tb(option_id, item_name) VALUES (4, '[현장수령형] 1월 25일 스토리움 *23#부스');

INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (0, 25000, NOW(), '2024-01-26 00:00:00', '2024-01-27 00:00:00', 1, '2024-01-13 00:00:00', 361, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/케이스1.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/케이스상세설명.jpg', '휴대폰 케이스는 우리 생활에서 빠질 수 없는 부분이 되었고, 이를 더 친환경적으로 만들어 보았습니다. 휴지를 재활용하여 자연 분해되는 휴대폰 케이스를 사용해보세요!', '자연을 사랑하는 마음을 담은 휴지로 만든 휴대폰 케이스', 'GIFT');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (3, '휴대폰 케이스', 25000, 1, true);
INSERT INTO item_tb(option_id, item_name) VALUES (5, '[현장수령형] 1월 25일 스토리움 *23#부스');

INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (0, 100000, NOW(), '2024-01-26 00:00:00', '2024-01-27 00:00:00', 1, '2024-01-13 00:00:00', 361, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/기린2.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/기린상세설명_page-0001.jpg', '우리의 친구 ‘기리니’는 매일 많은 양의 신선한 식료품을 필요로 합니다. 그러나 식량 구입 비용이 점점 더 부담스러워져 어려움을 겪고있습니다. 기린에게 필요한 사료를 구입하는데 도움을 주세요!', '우리의 ‘기리니’에게 사료를 선물해주세요!', 'DONATE');

INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (0, 75000, NOW(), '2024-01-26 00:00:00', '2024-01-27 00:00:00', 1, '2024-01-13 00:00:00', 361, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/팀사진.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/팀상세설명.jpg', '강도희, 곽민주, 박건규로 구성된 팀, *23#팀의 매력을 얻어가세요!', '*23#팀의 관심과 사랑을 받아가세요!', 'GIFT');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (5, '도희', 10000, 1, false);
INSERT INTO item_tb(option_id, item_name) VALUES (6, '관심의 인삿말 1회');
INSERT INTO item_tb(option_id, item_name) VALUES (6, '사랑의 눈길 1회');
INSERT INTO item_tb(option_id, item_name) VALUES (6, '하루동안 TMI 금지');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (5, '민주', 10000, 1, false);
INSERT INTO item_tb(option_id, item_name) VALUES (7, '다낭에서의 인삿말 1회');
INSERT INTO item_tb(option_id, item_name) VALUES (7, '다낭에서의 사랑의 눈길 1회');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (5, '건규', 10000, 1, false);
INSERT INTO item_tb(option_id, item_name) VALUES (8, '관심: 어! 너 오늘 ~한 것 같아!');
INSERT INTO item_tb(option_id, item_name) VALUES (8, '사랑: 개발보다 너가 더 좋아.');
INSERT INTO item_tb(option_id, item_name) VALUES (8, '공감: 아! 그랬구나!');

INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (0, 400000, NOW(), '2024-12-26 00:00:00', '2024-01-27 00:00:00', 1, '2024-01-13 00:00:00', 361, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/고양이.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/고양이상세설명_page-0001.jpg', '안녕하세요, 기린대 학생 여러분! 유기묘 문제를 해결하고, 고양이들의 건강과 행복을 증진시키기 위해 펀딩을 열었습니다.', '예대 냥이를 위한 중성화 펀딩에 동참해주세요!', 'DONATE');

INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (100000, 100000, NOW(), '2024-02-26 00:00:00', '2024-01-27 00:00:00', 1, '2024-01-13 00:00:00', 219, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/에코노.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/에코노상세설명.jpg', '전남대의 IT 동아리 에코노베이션을 소개합니다. 전공 무관, 당신이 IT 개발에 관심만 있다면 언제든지 환영합니다.', '에코노베이션을 알립니다!', 'DONATE');

INSERT INTO funding_tb(current_money, goal_money, created_at, end_time, estimated_start_time, member_id, start_time, university_id, image, long_description, short_description, title, funding_type) VALUES (0, 150000, NOW(), '2024-01-26 00:00:00', '2024-01-27 00:00:00', 1, '2024-01-13 00:00:00', 219, 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/사탕.jpg', 'https://girin-grim.s3.ap-northeast-2.amazonaws.com/funding/사탕상세설명_page-0001.jpg', '달달한 사탕이 추운 겨울날 지친 당신에게 활기를 찾아줄거에요. 맛있는 사탕! 위대한 사탕!', '일상에 달달한 활기 어떠세요?', 'GIFT');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (8, '과일의 활기', 20000, 20, false);
INSERT INTO item_tb(option_id, item_name) VALUES (9, '청포도 사탕 1pc');
INSERT INTO item_tb(option_id, item_name) VALUES (9, '딸기 사탕 1pc');
INSERT INTO item_tb(option_id, item_name) VALUES (9, '레몬 사탕 1pc');
INSERT INTO option_tb(funding_id, name, price, quantity, is_pickup) VALUES (8, '카페인의 활기', 20000, 10, false);
INSERT INTO item_tb(option_id, item_name) VALUES (10, '커피 사탕 3pc');





